### ISSUE TITLE
Does it work on Mac Yosemite?

### ISSUE THREAD

**Issue by carochicca** [mbi2gs/netlogo-matlab-extension#3]

**Comment by carochicca** [comment]
I got the warning "You are attempting to open a netlogo extension file that was created for a different version of the Netlogo extension API.  (This Netlogo uses API 5.0; the extension uses netlogo extension API 5.03.) Netlogo can try to load the extension, but it might not work.", using Netlogo 5.0.4 and Matlab R2013a, and then Netlogo crashes.

**Comment by mbi2gs** [comment]
That warning comes up even during normal conditions, and doesn't have anything to do with the crash. I haven't ever tried it on Yosemite... I assume NetLogo is working fine on its own? I've heard that upgrading to Yosemite often causes NetLogo to stop working, and it's just a matter of updating Java.

**Comment by mbi2gs** [comment]
Also, does Matlab open up? If so, what text does it display?

**Comment by carochicca** [comment]
NetLogo is working well, I only have problems with the extension. In order to write my model and get inputs from Matlab and vice versa, I select the “Code” tab and enter the line “extensions [matlab]” but, after that warning, NetLogo stops working and no Matlab window opens.

**Comment by mbi2gs** [comment]
Okay, I'll look into it.

**Comment by mbi2gs** [comment]
I just recompiled the extension using the newest Java package, and it works well with my NetLogo 5.3.1 and Matlab R2013a. Try replacing the matlab.jar file in your extensions folder with the newest one, and let me know if it works for you.

**Comment by carochicca** [comment]
Done and I got the following internal error with both NetLogo 5.0.4 and 5.2.1. 
NetLogo doesn't crash but Matlab is still not responding. I will try on Window and let you know. Thanks.
 
"NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.UnsupportedClassVersionError: matlabExtension : Unsupported major.minor version 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
 at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:627)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 at org.nlogo.workspace.ExtensionManager.getClassManager(ExtensionManager.java:404)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:170)
 at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
 at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
 at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
 at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.java:107)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.java:87)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.java:309)
 at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:175)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.app.ProceduresTab$CompileAction.actionPerformed(ProceduresTab.scala:59)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
 at ch.randelshofer.quaqua.QuaquaButtonListener.mouseReleased(QuaquaButtonListener.java:110)
 at java.awt.Component.processMouseEvent(Component.java:6414)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
 at java.awt.Component.processEvent(Component.java:6179)
 at java.awt.Container.processEvent(Container.java:2084)
 at java.awt.Component.dispatchEventImpl(Component.java:4776)
 at java.awt.Container.dispatchEventImpl(Container.java:2142)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
 at java.awt.Container.dispatchEventImpl(Container.java:2128)
 at java.awt.Window.dispatchEventImpl(Window.java:2492)
 at java.awt.Component.dispatchEvent(Component.java:4604)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:676)
 at java.awt.EventQueue$2.run(EventQueue.java:674)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:690)
 at java.awt.EventQueue$3.run(EventQueue.java:688)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

NetLogo 5.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-466.1-11M4716)
operating system: Mac OS X 10.10.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

11:13:27.981 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:13:27.981 CompileAllEvent (org.nlogo.app.MainProceduresTab) AWT-EventQueue-0
11:13:27.947 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:27.746 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:27.544 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:27.343 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:27.141 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:26.940 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:26.739 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:13:26.538 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0"

**Comment by mbi2gs** [comment]
Were you able to get things working?

**Comment by carochicca** [comment]
Not yet on my Mac laptop. Matlab is still not charging after the Netlogo extension command. I suppose this can be solved on Windows but I had no chance to try.

**Comment by mbi2gs** [comment]
I don't really have access to a newer Mac right now, but people are having trouble running things on Sierra, too. I would recommend using a windows PC if you can. Otherwise, the Mac updates will have to wait until I can get access to a Mac.
